# This file is part of the YesWiki Extension Hpf.
#
# Authors : see README.md file that was distributed with this source code.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
parameters:
  GroupsAdminsSuffixForEmails: ''        # Feature UUID : hpf-area-management
  AreaFieldName: ''                      # Feature UUID : hpf-area-management
  PostalCodeFieldName: 'bf_code_postal'  # Feature UUID : hpf-area-management
  departmentListName: 'ListeDepartementsFrancais' # Feature UUID : hpf-area-management
  formIdAreaToDepartment: ''             # Feature UUID : hpf-area-management
  hpf:
    structureInfo:                         # Feature UUID : hpf-receipts-creation
      name: ''
      address: ''
      addressComplement: ''
      postalCode: ''
      town: ''
      email: ''
      website: ''
  hpf_editable_config_params:
    - hpf:
      - contribFormIds
      - paymentsFormUrls
      - paymentMessageEntry
      - structureInfo:                # Feature UUID : hpf-receipts-creation
        - 'name'
        - 'address'
        - 'addressComplement'
        - 'postalCode'
        - 'town'
        - 'email'
        - 'website' 
    - 'AreaFieldName'               # Feature UUID : hpf-area-management
    - 'PostalCodeFieldName'         # Feature UUID : hpf-area-management
    - 'GroupsAdminsSuffixForEmails' # Feature UUID : hpf-area-management

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Hpf\Service\:
    resource: 'services/*'
    exclude:
     - 'GroupManagementServiceInterface.php' # Feature UUID : hpf-area-management

  # Allows to use controllers as services
  YesWiki\Hpf\Controller\:
    resource: 'controllers/*'

  # replace usage of HelloAssoService by hpf one to prevent errors if shop not installed
  YesWiki\Hpf\Service\HelloAssoService:
    decorates: YesWiki\Shop\Service\HelloAssoService
    decoration_on_invalid: null
    arguments: ['@.inner']
    factory: ['@YesWiki\Hpf\Service\HelloAssoServiceFactory','create']

  YesWiki\Hpf\Service\ActionsBuilderService:
    decorates: YesWiki\Aceditor\Service\ActionsBuilderService
    decoration_on_invalid: null
    arguments:
      $parentActionsBuilderService: '@.inner'
  
  # Feature UUID : hpf-area-management
  YesWiki\Hpf\Service\GroupManagementService:
    decorates: YesWiki\Groupmanagement\Service\GroupManagementService
    decoration_on_invalid: null
  YesWiki\Hpf\Controller\GroupController:
    tags:
      - { name: yeswiki.event_subscriber }
  YesWiki\Hpf\Controller\DisplayEmailController:
    tags:
      - { name: yeswiki.event_subscriber }

