# This file is part of the YesWiki Extension Hpf.
#
# Authors : see README.md file that was distributed with this source code.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
parameters:
  hpf_editable_config_params:
    - hpf:
      - contribFormId
      - paymentFormUrl

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Hpf\Service\:
     resource: 'services/*'

  # Allows to use controllers as services
  YesWiki\Hpf\Controller\:
    resource: 'controllers/*'

  # replace usage of HelloAssoService by hpf one to prevent errors if shop not installed
  YesWiki\Hpf\Service\HelloAssoService:
    decorates: YesWiki\Shop\Service\HelloAssoService
    decoration_on_invalid: null
    arguments: ['@.inner']
    factory: ['@YesWiki\Hpf\Service\HelloAssoServiceFactory','create']

  # replace usage of Core Comment Service by webhooks one to force registration of event listeners
  # ignore if core CommentService is not existing
  YesWiki\Hpf\Controller\ApiController:
    decorates: YesWiki\Shop\Controller\ApiController
    decoration_on_invalid: ignore
    arguments: ['@.inner']
    factory: ['@YesWiki\Hpf\Controller\HelloAssoController','bindObject']
